export const seoData = {
  home: {
    title: 'Email & SMS for Growing e-commerce brands | Mailerblend',
    description: 'All-in-one email & SMS platform for SMBs. Build, automate, and analyze campaigns with no code. Fast setup, high deliverability, SMB-friendly pricing.',
    canonicalUrl: 'https://www.mailerblend.com/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/home.jpg',
    h1: 'All the tools to grow your e-commerce',
    heroHeadline: 'Turn emails & SMS into predictable revenue',
    heroSubheadline: 'Launch beautiful campaigns, automate journeys, and track ROI—without a developer.',
  },
  marketingAutomation: {
    title: 'Marketing Automation for SMBs—Journeys, Triggers & Templates | Mailerblend',
    description: 'Build customer journeys in minutes. 50+ templates, real-time triggers, segmentation, and goal tracking. No code required.',
    canonicalUrl: 'https://www.mailerblend.com/email-marketing-automation/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/marketing-automation.jpg',
    h1: '#1 Email Automation Platform for SMBs',
    heroHeadline: 'Automate the right message at the right time',
    heroSubheadline: 'Pick a template, connect your stack, and go live in minutes.',
  },
  reportingAnalytics: {
    title: 'Email Analytics & Reporting—Opens, Clicks, Deliverability | Mailerblend',
    description: 'Real-time dashboards for open/click rates, bounces, geos, devices. Export reports, access analytics via API, and optimize with split testing.',
    canonicalUrl: 'https://www.mailerblend.com/email-analytics-reporting/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/reporting-and-analytics.jpg',
    h1: 'See what drives performance—instantly',
    heroHeadline: 'Every email is a learning loop',
    heroSubheadline: 'Measure, iterate, and grow with real-time insights.',
  },
  security: {
    title: 'Enterprise-grade Security for SMB Email & SMS | Mailerblend',
    description: 'AWS-backed infrastructure, regular pen tests, 2FA, data ownership, anti-spam, and GDPR resources to safeguard your data and reputation.',
    canonicalUrl: 'https://www.mailerblend.com/email-security-deliverability/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/security.jpg',
    h1: 'Security built into every layer',
    heroHeadline: 'Protect customer trust at scale',
    heroSubheadline: 'Modern controls to keep your data safe and your email reputation strong.',
  },
  integrations: {
    title: 'Integrations for Your Stack—CRM, E-commerce, Dev Tools | Mailerblend',
    description: 'Connect WooCommerce, Shopify, WordPress, Laravel, Zapier/Make, Slack, and more. Trigger emails/SMS from any app—no heavy lifting.',
    canonicalUrl: 'https://www.mailerblend.com/email-marketing-integrations/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/integrations.jpg',
    h1: 'Make your life easy—integrate your favorite tools',
    heroHeadline: 'Plug in and go further',
    heroSubheadline: 'Ship customer journeys that pull data from your apps in a few clicks.',
  },
  dedicatedIp: {
    title: 'Dedicated IP for High-Volume Senders—Reputation & Warm-Up | Mailerblend',
    description: 'Own your reputation with a dedicated IP. Warm-up guidance, monitoring, and support to maximize inbox placement for 150k+ emails/month.',
    canonicalUrl: 'https://www.mailerblend.com/dedicated-ip/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/dedicated-ip.jpg',
    h1: 'Take control with your own IP',
    heroHeadline: 'Your reputation, your rules',
    heroSubheadline: 'Dedicated IPs and expert warm-up plans for consistent inboxing.',
  },
  pricing: {
    title: 'Simple Pricing for SMBs—Start Free, Scale as You Grow | Mailerblend',
    description: 'Clear plans with no contracts. Start free, then upgrade for advanced automation, analytics, SMS, and support. Annual discounts available.',
    canonicalUrl: 'https://www.mailerblend.com/pricing/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/pricing.jpg',
    h1: 'We cut prices, not features',
    heroHeadline: 'Pick a plan that fits today—and tomorrow',
    heroSubheadline: 'Transparent pricing, flexible credits, and room to grow.',
  },
  contact: {
    title: 'Contact Support & Sales—We\'re Here to Help | Mailerblend',
    description: 'Need help with campaigns, deliverability, or setup? Contact support or sales. Faster help when you sign in to your account.',
    canonicalUrl: 'https://www.mailerblend.com/contact/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/contact-us.jpg',
    h1: 'Contact us',
    heroHeadline: 'Talk to a human',
    heroSubheadline: 'Get answers on setup, deliverability, and strategy—fast.',
  },
  login: {
    title: 'Log in to Mailerblend',
    description: 'Access your account to manage campaigns, automations, analytics, and billing securely.',
    canonicalUrl: 'https://www.mailerblend.com/login/',
    robots: 'noindex, nofollow',
    ogImage: 'https://www.mailerblend.com/og/login.jpg',
    h1: 'Enter your login details',
  },
  signup: {
    title: 'Create your Mailerblend Account—Start Free',
    description: 'Get started in minutes. Build emails, automate journeys, and send with best-in-class deliverability—no credit card required.',
    canonicalUrl: 'https://www.mailerblend.com/signup/',
    robots: 'noindex, nofollow',
    ogImage: 'https://www.mailerblend.com/og/signup.jpg',
    h1: 'Create Account',
  },
  smtpRelay: {
    title: 'Free SMTP Relay—Fast, Reliable Transactional Email | Mailerblend',
    description: 'Connect in minutes via SMTP or API. TLS/SSL ports, SPF/DKIM/DMARC, real-time analytics, and 24/7 support for high deliverability.',
    canonicalUrl: 'https://www.mailerblend.com/smtp-relay/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/smtp-relay.jpg',
    h1: 'Free SMTP server to power your emails',
    heroHeadline: 'Plug-and-play SMTP that scales with you',
    heroSubheadline: 'Connect any MTA, authenticate your domain, and start landing in the inbox.',
  },
  smsApi: {
    title: 'Transactional SMS API—OTP, Alerts & Notifications | Mailerblend',
    description: 'Send high-deliverability transactional SMS at scale. OTP/2FA, alerts, reminders, replies, webhooks, templates & personalization.',
    canonicalUrl: 'https://www.mailerblend.com/transactional-sms-api/',
    robots: 'index, follow',
    ogImage: 'https://www.mailerblend.com/og/sms-api.jpg',
    h1: 'Reach more customers with transactional messaging',
    heroHeadline: 'Right message. Right phone. Right now.',
    heroSubheadline: 'Developer-friendly API, global coverage, and smart delivery for time-critical texts.',
  },
};
